### ISSUE TITLE
コンペの特徴について

### ISSUE THREAD

**Issue by TanimotoRui** [meltyyyyy/ICR-2023#1]
- trainデータが約600
- 2値分類タスクにおいて、目的変数が不均衡
→cv, lbの動きを丁寧にみて過学習を抑制する必要があり(shake down, shake upが起こりやすい)
- 対策としては、loss関数の重みづけ, ダウンサンプリング, post processが取り上げられている
（ちょっとpost processは初めてみたから追いつけてない。。。明日以降ちゃんと調べます）

<参考>
- [How To Balance Training And Boost CV and LB Score!](https://www.kaggle.com/competitions/icr-identify-age-related-conditions/discussion/412507)
- [🏆 A Similar Competition (medical analysis) competition winner solution 🏆](https://www.kaggle.com/competitions/icr-identify-age-related-conditions/discussion/409596)

**Comment by meltyyyyy** [comment]
確認した ! どうも !
