### ISSUE TITLE
K-Means&集約特徴量の追加

### ISSUE THREAD

**Issue by TanimotoRui** [meltyyyyy/ICR-2023#11]
- [x] add k-means
- [x] add aggrigation feature

**Comment by TanimotoRui** [comment]
メモ
K-Meansは年齢+ラベルの2次元データで教師なし学習( -> リークする？？？)
ラベルごとに各集約特徴量の追加を実施

**Comment by TanimotoRui** [comment]
K-Meansは年齢+ラベルの2次元データでkmeansの意図としては、年齢と病気の有無の関係性から適切な区分け(層)で分けたいという意図。どうなんだろう、他にいい案があるか？？あんまりデータの前処理のディスカッション上がってない気がするからもう少しディスカッション読んでから着手

**Comment by TanimotoRui** [comment]
特徴量追加に関して参考
https://zenn.dev/colum2131/articles/fffac4654e7c7c

**Comment by TanimotoRui** [comment]
@meltyyyyy 
https://www.kaggle.com/code/ruiruidayoooo/exp002-kmeans-agg/edit/run/136187341

上記Notebookなんだけど、あまりにも精度悪くなってるから、一回コード簡単にみてもらえるかな？？
たけるのアカウントにcodeの共有送ったから見れるはず！！

kaggle notebookの方がversionとかもあってみやすいかなと思ってこれで共有してみたんだけど、普通にみにくかったらgithubに戻すから言ってもらえると！

**Comment by meltyyyyy** [comment]
@TanimotoRui 

CVは0.13くらいな気がするけど, ここでいう精度ってLBのこと?

```
Fold: 0, log loss: 0.193, balanced los loss: 0.134
Fold: 1, log loss: 0.203, balanced los loss: 0.158
Fold: 2, log loss: 0.182, balanced los loss: 0.123
Fold: 3, log loss: 0.099, balanced los loss: 0.098
Fold: 4, log loss: 0.235, balanced los loss: 0.143

Log Loss
[0.1930217558117216, 0.20255809244604747, 0.1824163283272225, 0.09876060801043407, 0.2346270178141627]
0.18227676048191765 0.045259924870579615

Balanced Log Loss
[0.13439783441543068, 0.1581030925734695, 0.12346086187902981, 0.0978694305313354, 0.14263872107459508]
MEAN :  0.13129398809477208 STD :  0.02017733295526792
```

train -> train_dropped でデータ数が60個減ってる. 60/617だから10%もデータが減ったことになっているので, 単純にデータ数が少なくなって精度劣化したのでは?

**Comment by TanimotoRui** [comment]
そうそう。LB。
確かにそうだな、純粋にデータ数少なくなって精度落ちたんだね。

ちょっと一旦データ数少なくなるベクトルの前処理しない方向で。

終盤に色々試しましょう。
整理して最後またメンション立てます。

**Comment by TanimotoRui** [comment]
@meltyyyyy 
PR含め確認お願いします！
結果は、lb .30でかなり悪化。
cvは.11くらいなんだけど、過学習してるみたい

一旦スコア高いnotebookの分析に入って、さわれたら特徴削減に進みます
確認したらcloseよろ〜

**Comment by meltyyyyy** [comment]
@TanimotoRui 

このCV使ったらどんなかんじだろう ? 前使っていたやつよりよりロバストなはず.

https://github.com/meltyyyyy/ICR-2023/pull/13

**Comment by TanimotoRui** [comment]
@meltyyyyy 
おけ！試してみます！

**Comment by TanimotoRui** [comment]
@meltyyyyy 
修正までかけた！結果は明日以降確認するので、諸々指標整理してクローズします
