### ISSUE TITLE
ChatGPTのCode InterpreterによるEDAを試してみる

### ISSUE THREAD

**Issue by meltyyyyy** [meltyyyyy/ICR-2023#14]

**Comment by meltyyyyy** [comment]
@TanimotoRui 

これはやばすぎる... ぜひ確認してほしい !

https://chat.openai.com/share/76d0393b-2e6c-48d1-a878-fbf91dc8b6e2

**Comment by TanimotoRui** [comment]
すげえ笑
いやまあ流石に何が書いてあるかは大体全部わかるんだけど、一部特徴選択とかは普通に知らん知識やったし、これフリーアクセスできる時代やべえな。

**Comment by TanimotoRui** [comment]
あ、閉じます
