### ISSUE TITLE
複数モデルの精度比較

### ISSUE THREAD

**Issue by TanimotoRui** [meltyyyyy/ICR-2023#18]
- [ ] lgb
- [ ] xgb
- [ ] catboost
- [ ] tabpfn
- [ ] ロジスティク回帰

**Comment by TanimotoRui** [comment]
参考 : https://www.kaggle.com/code/muelsamu/simple-tabpfn-approach-for-score-of-15-in-1-min

**Comment by TanimotoRui** [comment]
@meltyyyyy 
個人的にtabpfnは初めて聞く手法で単純に試してみたいんだけど、kaggleカーネルでなぜかimportできずエラーが返される。。。苦戦中です。。。

**Comment by meltyyyyy** [comment]
@TanimotoRui 

これってなんで精度比較してるんだっけ？目的と仮説(あれば)を知りたいかも !

**Comment by TanimotoRui** [comment]
@meltyyyyy 
クラスタリング+集約特徴量の追加がlbの向上に寄与しなかったんだけど、lgbと相性が悪いだけで、他のでは寄与するとかあるのかなと思って複数見てみたかった！

あんまりlbにこだわりすぎてもだけど、挙動は見たいなって！

**Comment by TanimotoRui** [comment]
これアンサンブルの方で共有します！
