### ISSUE TITLE
予測分布の可視化を行う

### ISSUE THREAD

**Issue by meltyyyyy** [meltyyyyy/ICR-2023#28]

**Comment by meltyyyyy** [comment]
## 予測分布の可視化

特徴量エンジニアリングなし

### Inner Fold 80 %

![pred_dist0_80](https://github.com/meltyyyyy/ICR-2023/assets/81362789/57323b0c-2911-4531-8c10-e971729d6b70)

### Outer Fold 20 %

![pred_dist0_20](https://github.com/meltyyyyy/ICR-2023/assets/81362789/639eb8db-c3cc-4134-a643-817871124e3f)

**Comment by meltyyyyy** [comment]
## 考察

- 予測が間違っている場合において, かなり自信を持って間違っている場合が多い. これはbalanced_log_lossだと致命的なスコアに繋がる.
- ラベル0の予想が思ったより自信がなさそう. Postprocess が効く理由がこれだと思う.
- 出力の分布見ながらモデリングするのが大切だと思う. 特徴量の削減やアンサンブルによって分布の変化を目指せるか確認するべきだと思った.

**Comment by meltyyyyy** [comment]
@TanimotoRui 

確認やコメント(あれば)とアンサンブル時の予測分布の可視化をお願いしたい !

**Comment by meltyyyyy** [comment]
## 予測分布の可視化

特徴量削減後に一番性能が良かったもの

```
['DE', 'EL', 'GH', 'FE', 'DY', 'EE', 'EU', 'CH', 'CD ', 'CC', 'GL', 'DL',
       'EB', 'AF', 'FI', 'DN', 'DA', 'FL', 'CR', 'FR', 'AB', 'BQ', 'DU']
```

### Inner Fold 80 %

![pred_dist0_80](https://github.com/meltyyyyy/ICR-2023/assets/81362789/b491d55b-3922-4883-b288-671a6582a727)

### Outer Fold 20 %

![pred_dist0_20](https://github.com/meltyyyyy/ICR-2023/assets/81362789/ba84b3ff-0a7c-42b5-b318-b86c1f36bf05)

**Comment by meltyyyyy** [comment]
あまり予測分布に変化はなさそう

**Comment by TanimotoRui** [comment]
@meltyyyyy サンキュ！一旦今
- lgb
- xgb
- cat
- tabpfn
- ロジスティク回帰

まで終わったからそれぞれの分布と

- 単純な予測値の足し合わせの平均アンサンブル
- スタッキング

の分布まで可視化して日曜とさせていただきます！

**Comment by TanimotoRui** [comment]
@meltyyyyy サンキュ！一旦今
- lgb
- xgb
- cat
- tabpfn
- ロジスティク回帰
まで終わったからそれぞれの分布と
- 単純な予測値の足し合わせの平均アンサンブル
- スタッキング
の分布まで可視化して日曜とさせていただきます！

**Comment by TanimotoRui** [comment]
これもしouterの方で一定自信を持って予測できるような分布になればpostprocess効果的かもね
