### ISSUE TITLE
集約特徴量の追加と削減による精度変化を調査する

### ISSUE THREAD

**Issue by meltyyyyy** [meltyyyyy/ICR-2023#29]

**Comment by meltyyyyy** [comment]
## 実験内容

数値を取るカラムに対して集約特徴量(mean, sum, std)を計算し241個の特徴量を作成した.
特徴量を5つづつ減らしながらスコアをプロットした


![feat_reduction](https://github.com/meltyyyyy/ICR-2023/assets/81362789/93578acb-83f3-4359-9cda-136a859aea5d)
![feat_imps](https://github.com/meltyyyyy/ICR-2023/assets/81362789/84422ce5-2e88-440c-a97d-205d8563d9e7)

**Comment by meltyyyyy** [comment]
## 考察

残った特徴量を見るに集約系の特徴量は全て効いていない. 集約特徴量は使わない方向で良いと思った.

**Comment by TanimotoRui** [comment]
あざます。前に相関で落とした時も30カラムまで絞った時に入ってたの1 or 2くらいだったので違和感ないです。
