### ISSUE TITLE
post processing

### ISSUE THREAD

**Issue by TanimotoRui** [meltyyyyy/ICR-2023#4]
- 多くのnotebookは過学習している可能性が高い([たけるのissueでも言及](https://github.com/meltyyyyy/ICR-2023/issues/3#issuecomment-1617016622))
- 原因は、確率値としての予測値のうち、任意の閾値より上、下の予測値を0, 1に丸めていることである
- うまく作用した場合はいいが、特に少数ラベルを誤差を大きくする後処理をしてしまった場合(本来は0.01と予測されている1ラベルなど)大きく予測を悪化させる

以下引用(日本語訳)
>なぜ架空のテストセットで後処理をした後にloglossがそんなに増加したのかがわかりません。というのも、視覚的に言えば、テストセットのClass_0を0-0.029以内の0に分類しただけで、理想的にはスコアが向上するはずだからです。**p[Class_1]=0.022から0.0に移動した間違った予測は1つしかないようです。**ということは、**0.028以内の多くの正しい予測を改善することと、0.022の間違った予測を移動することは、スコアをほぼ2倍に悪化させる選択ということでしょうか？**

>balanced_log_lossの "log_loss "に起因するもので、閾値を変更したときにスコアを決定する関数のため、正しい予測がわずかに正しくなり、したがってスコアがわずかに変わるだけです。しかし、もし閾値を大きくしすぎて一度でも間違ってしまうと、すでに間違っているポジションを取り、実質的にそのポジションを二度取ることになる。つまり、70％の確率で間違っていると言う代わりに、100％の確率で間違っていると言うようなものだ。99％の確信から100％の確信に変わる間、あなたは正しいことを得るのだ。

[引用元スレッド](https://www.kaggle.com/competitions/icr-identify-age-related-conditions/discussion/414209#2323894)

参考
- [Postprocessing risk explained](https://www.kaggle.com/competitions/icr-identify-age-related-conditions/discussion/414209)

**Comment by TanimotoRui** [comment]
### lb best scoreのnotebookについて

やってることは非常にシンプル
- カテゴリカルカラムに対するラベルエンコーディング
- ダウンサンプリング
- アンサンブル(シンプルな確率値のmean)

個人的に怖いのが下記。かなり大きい幅を0, 1に丸めていて、lbとprivateの乖離を引き起こす可能性が大きいと思う。ただ、まだ諸々の可視化がうまくみれていないため、自分の理解としては、非常に気をつけないといけないが、絶対に実施してはいけないというわけではない。今後用検証、くらいの感覚。

```
#y_pred=np.mean(y_pred_list, axis=0)
probabilities = np.concatenate((y_pred[:,:1], np.sum(y_pred[:,1:], 1, keepdims=True)), axis=1)
p0 = probabilities[:,:1]
p0[p0 > 0.60] = 1
p0[p0 < 0.25] = 0
```

参考
- [public_krni_pdi_:( with two additional models](https://www.kaggle.com/code/aikhmelnytskyy/public-krni-pdi-with-two-additional-models)

**Comment by meltyyyyy** [comment]
僕も[Postprocessing risk explained](https://www.kaggle.com/competitions/icr-identify-age-related-conditions/discussion/414209)を読んだんだけど, 一旦Postprocessingはなしで良い気がするのんだけどいかが?

**Comment by TanimotoRui** [comment]
@TanimotoRui 
大丈夫だと思う！あんまりそこに時間使いすぎるのは違う気がするし、最後時間余ってちゃんとディスカッションできれば採用しよう。
