### ISSUE TITLE
CVを実装する

### ISSUE THREAD

**Issue by meltyyyyy** [meltyyyyy/ICR-2023#6]

**Comment by meltyyyyy** [comment]
やはりBNカラムが年齢だと仮定すると高齢になるに連れて病気持ちが多くなる分布になっているから納得感がある

<img width="651" alt="スクリーンショット 2023-07-05 8 34 09" src="https://github.com/meltyyyyy/ICR-2023/assets/81362789/b5533534-17e0-46fb-bfba-5f26fab3efb9">

**Comment by TanimotoRui** [comment]
あ、作業途中かな〜って思ったらとりあえず最後のアウトプットにスタンプ押してくし、作業完了のタイミングでメンション飛ばしてくれると！

**Comment by meltyyyyy** [comment]
### Grreks のAlphaカラム

<img width="460" alt="スクリーンショット 2023-07-07 8 19 47" src="https://github.com/meltyyyyy/ICR-2023/assets/81362789/07cb3079-cfe6-4cb0-8c17-a059b522e69a">

**Comment by meltyyyyy** [comment]
@TanimotoRui 

作業完了してるからクローズします
