### ISSUE TITLE
stratified down-sampling

### ISSUE THREAD

**Issue by TanimotoRui** [meltyyyyy/ICR-2023#8]
# 結果v1 : データ数の比率 -> class_0 : class_1 = 127 : 108

Balanced Log Loss
- fold1 : 0.39318688101590527
- fold2 : 0.2522475933793796
- fold3 : 0.25053201392786434
- fold4 : 0.30173099244476415
- fold5 : 0.2390629239207889

MEAN :  0.28735208093774045, STD :  0.05714480391158345

CV : 0.27

感想
- 精度は全然良くないけど、lbとcvの差は小さい
- 過学習は抑制できてる？？
- 今回class0->約120データ, class1->約110データで割と均等に配分
- subがアメリカ時間？かなんかで1しかできずcvしか試せてないけど、cvはやっぱりデータ多く使う方がlossは下がる傾向に

# その他実験
class_0 : class_1 = 254 : 108
Balanced Log Loss
[0.23085570535544403, 0.22138108515767435, 0.15031516152189964, 0.24798517929050976, 0.13740997897869234]
MEAN :  0.197589422060844 STD :  0.044875031505466366

class_0 : class_1 = 381  : 108
Balanced Log Loss
[0.12205471487516421, 0.16487030986518764, 0.09028501278059935, 0.16704096179844805, 0.18300132594449228]
MEAN :  0.1454504650527783 STD :  0.03418752792098041

USE ALL
Balanced Log Loss
[0.1728986546015431, 0.1712575409961535, 0.03206591072231473, 0.12272869142311414, 0.11400946470353504]
MEAN : 0.12259205248933211 STD : 0.05131811729634114

**Comment by meltyyyyy** [comment]
逆にアップサンプリングできないかな笑

**Comment by meltyyyyy** [comment]
@TanimotoRui 

これってCV何で分けている?

**Comment by TanimotoRui** [comment]
@meltyyyyy 
CVは年齢層ラベルをターゲットにstratified k foldしてる！

データオーグメンテーションできるとつよいなあ
